### ISSUE TITLE
[Mini Project] 8x8 LED module + Joistick

### ISSUE THREAD

**Issue by weyoui** [weyoui/mbedTrust#51]
This project is about the implementation and test on Digital Input/Output.

- 8x8 Led module : 2.89$ / 5 pcs (0.58 $ / 1pcs) for digital output
- Joistick module : 5.0$/ 10 pcs (0.5$ / 1pcs) for digital input

We can make several scenario.
 - When user moves joistick, then Led on 8x8 Led module is moving that direction.
 - We can create a game like tetris or something interesting mini game.

**Comment by ghost** [comment]
Here is the schematic reference material.
https://www.aliexpress.com/item/Best-Price-10-pcs-8x8-Mini-Dot-Matrix-LED-Display-Red-Common-Anode-16-pin/1679655587.html?spm=2114.13010608.0.0.V0D2mv
